# Documentation: https://roots.io/trellis/docs/vault/
vault_mail_password: smtp_password

# Variables to accompany `wordpress_env_defaults` in `group_vars/all/helpers.yml`
# Note: These values can be overriden by `vault_wordpress_sites.*.env`
#
# vault_wordpress_env_defaults:
#   my_api_key: 'available to all environments'

# Composer authentication for all environments
# Note: These values can be also be set for each environment by `vault_wordpress_sites.*.composer_authentications`
#
# vault_composer_authentications:
#   - { hostname: satis.example.com, username: foo, password: bar }
